"""Portable Markdown context export for Human-Guided Protein Design projects."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from human_protein_design.archive.store import DesignArchive


def format_date(timestamp: str) -> str:
    """Return YYYY-MM-DD from an ISO timestamp."""
    return timestamp.split("T", 1)[0]


def _markdown_value(value: Any) -> str:
    """Render a compact value without losing structured information."""
    if isinstance(value, (dict, list)):
        return json.dumps(value, ensure_ascii=False, sort_keys=True)
    return str(value)


def _latest_delta_score(archive: DesignArchive, design_id: str) -> float | None:
    """Return the newest archived computational mutation delta, if available."""
    for entry in reversed(archive.get_design_evidence(design_id)):
        if entry.source_type != "computational":
            continue
        value = entry.data.get("delta_score")
        if isinstance(value, (int, float)):
            return float(value)
    return None


def export_project_context(
    archive: DesignArchive,
    output_path: str | Path,
    project_name: str,
) -> Path:
    """Export one LLM-ready Markdown snapshot of the complete HGD project.

    The first part is deliberately readable by a scientist. The final JSON block
    contains the complete canonical archive state so an LLM or downstream tool
    does not have to infer information omitted by the human-readable summary.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    designs = sorted(archive.designs.values(), key=lambda item: item.created_at)
    accepted = sum(archive.get_decision_outcome(item.id) == "accepted" for item in designs)
    rejected = sum(archive.get_decision_outcome(item.id) == "rejected" for item in designs)
    deferred = sum(archive.get_decision_outcome(item.id) == "deferred" for item in designs)
    undecided = sum(archive.get_decision_outcome(item.id) is None for item in designs)

    lines: list[str] = [
        f"# {project_name} — HGD Project Context",
        "",
        "> Portable scientific context generated by Human-Guided Protein Design.",
        "> The readable sections summarize the project; the JSON appendix contains the complete archive state.",
        "",
        "## Project overview",
        "",
        f"- Archive schema: `{archive.SCHEMA_VERSION}`",
        f"- Designs: **{len(archive.designs)}**",
        f"- Structure models: **{len(archive.structures)}**",
        f"- Decisions: **{len(archive.decisions)}**",
        f"- Evidence entries: **{len(archive.evidence)}**",
        f"- Objectives: **{len(archive.objectives)}**",
        f"- Targets: **{len(archive.targets)}**",
        f"- Latest design decisions: {accepted} accepted · {rejected} rejected · {deferred} deferred · {undecided} undecided",
        "",
    ]

    lines.extend(["## Scientific objectives", ""])
    if not archive.objectives:
        lines.append("No project objectives recorded.")
    for objective in sorted(archive.objectives.values(), key=lambda item: item.created_at):
        lines.extend([
            f"### {objective.id}",
            "",
            objective.description,
            "",
            f"- Created: {format_date(objective.created_at)}",
            f"- Constraints: {', '.join(objective.constraints) if objective.constraints else 'none recorded'}",
        ])
        if objective.metadata:
            lines.append(f"- Metadata: `{_markdown_value(objective.metadata)}`")
        lines.append("")

    lines.extend(["## Targets", ""])
    if not archive.targets:
        lines.append("No molecular targets recorded.")
    for target in sorted(archive.targets.values(), key=lambda item: item.created_at):
        lines.extend([
            f"### {target.name}",
            "",
            f"- ID: `{target.id}`",
            f"- Created: {format_date(target.created_at)}",
            f"- Sequence: `{target.sequence}`" if target.sequence else "- Sequence: not recorded",
            f"- Structure: `{target.structure_path}`" if target.structure_path else "- Structure: not recorded",
        ])
        if target.notes:
            lines.append(f"- Notes: {target.notes}")
        if target.metadata:
            lines.append(f"- Metadata: `{_markdown_value(target.metadata)}`")
        lines.append("")

    lines.extend([
        "## Design index",
        "",
        "| Design | Lineage | Origin | Status | Latest decision | ΔScore | Structures | Evidence |",
        "|---|---|---|---|---|---:|---:|---:|",
    ])
    for design in designs:
        latest = archive.get_latest_decision(design.id)
        delta = _latest_delta_score(archive, design.id)
        lines.append(
            f"| {archive.get_design_label(design.id)} | {archive.get_lineage_label(design.id)} | "
            f"{design.origin} | {design.status} | {latest.outcome if latest else '—'} | "
            f"{delta:+.3f}" if delta is not None else
            f"| {archive.get_design_label(design.id)} | {archive.get_lineage_label(design.id)} | "
            f"{design.origin} | {design.status} | {latest.outcome if latest else '—'} | —"
        )
        if delta is not None:
            lines[-1] += f" | {len(archive.get_design_structures(design.id))} | {len(archive.get_design_evidence(design.id))} |"
        else:
            lines[-1] += f" | {len(archive.get_design_structures(design.id))} | {len(archive.get_design_evidence(design.id))} |"

    lines.extend(["", "## Design records", ""])
    for design in designs:
        label = archive.get_design_label(design.id)
        structures = archive.get_design_structures(design.id)
        decisions = archive.get_design_decisions(design.id)
        evidence = archive.get_design_evidence(design.id)

        lines.extend([
            f"### {label}",
            "",
            f"- ID: `{design.id}`",
            f"- Lineage: {archive.get_lineage_label(design.id)}",
            f"- Parent design: `{design.parent_design_id}`" if design.parent_design_id else "- Parent design: root",
            f"- Origin: {design.origin}",
            f"- Status: {design.status}",
            f"- Created: {format_date(design.created_at)}",
            f"- Objective ID: `{design.objective_id}`" if design.objective_id else "- Objective ID: none",
            f"- Target ID: `{design.target_id}`" if design.target_id else "- Target ID: none",
        ])
        if design.hypothesis:
            lines.append(f"- Design hypothesis: {design.hypothesis}")
        if design.sequence:
            lines.extend(["", "**Sequence**", "", f"`{design.sequence}`", ""])
        if design.metadata:
            lines.extend(["**Design metadata**", "", "```json", json.dumps(design.metadata, indent=2, ensure_ascii=False), "```", ""])

        lines.extend(["**Structures**", ""])
        if not structures:
            lines.append("- No first-class structure models recorded.")
        for structure in structures:
            confidence = []
            if structure.mean_plddt is not None:
                confidence.append(f"mean pLDDT={structure.mean_plddt:.2f}")
            if structure.ptm is not None:
                confidence.append(f"pTM={structure.ptm:.3f}")
            if structure.iptm is not None:
                confidence.append(f"ipTM={structure.iptm:.3f}")
            lines.append(
                f"- `{structure.structure_path}` — {structure.source}"
                + (f" · {structure.method}" if structure.method else "")
                + (f" · {', '.join(confidence)}" if confidence else "")
                + f" · ID `{structure.id}`"
            )
            if structure.notes:
                lines.append(f"  - Notes: {structure.notes}")
            if structure.pae_path:
                lines.append(f"  - PAE: `{structure.pae_path}`")
            if structure.metadata:
                lines.append(f"  - Metadata: `{_markdown_value(structure.metadata)}`")
        lines.append("")

        lines.extend(["**Decision history**", ""])
        if not decisions:
            lines.append("- No decisions recorded.")
        for number, decision in enumerate(decisions, start=1):
            lines.append(f"- **#{number} · {decision.outcome.upper()} · {format_date(decision.created_at)}**")
            if decision.objective:
                lines.append(f"  - Objective: {decision.objective}")
            if decision.hypothesis:
                lines.append(f"  - Hypothesis: {decision.hypothesis}")
            if decision.rationale:
                lines.append(f"  - Rationale: {decision.rationale}")
            if decision.program_comment:
                lines.append(f"  - Program comment: {decision.program_comment}")
            if decision.user_note:
                lines.append(f"  - User note: {decision.user_note}")
            if decision.metadata:
                lines.append(f"  - Metadata: `{_markdown_value(decision.metadata)}`")
        lines.append("")

        lines.extend(["**Evidence**", ""])
        if not evidence:
            lines.append("- No evidence recorded.")
        for entry in evidence:
            lines.append(
                f"- **{entry.source_name}** · {entry.source_type} · {format_date(entry.created_at)} · ID `{entry.id}`"
            )
            lines.append(f"  - Summary: {entry.summary}")
            if entry.notes:
                lines.append(f"  - Notes: {entry.notes}")
            if entry.structure_id:
                lines.append(f"  - Structure ID: `{entry.structure_id}`")
            if entry.decision_id:
                lines.append(f"  - Decision ID: `{entry.decision_id}`")
            if entry.target_id:
                lines.append(f"  - Target ID: `{entry.target_id}`")
            if entry.file_paths:
                lines.append("  - Files: " + ", ".join(f"`{path}`" for path in entry.file_paths))
            if entry.references:
                lines.append("  - References: " + ", ".join(entry.references))
            if entry.data:
                lines.extend(["  - Structured data:", "", "```json", json.dumps(entry.data, indent=2, ensure_ascii=False), "```"])
        lines.extend(["", "---", ""])

    lines.extend([
        "## Complete machine-readable archive",
        "",
        "This JSON block is the complete canonical archive state at export time. It is included so an LLM or downstream tool can recover IDs, links, metadata, numerical evidence, and provenance without relying on the prose summary.",
        "",
        "```json",
        json.dumps(archive.to_dict(), indent=2, ensure_ascii=False),
        "```",
        "",
    ])

    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path


# Temporary compatibility alias for old code/scripts. New code should use
# export_project_context and PROJECT_CONTEXT.md.
export_project_summary = export_project_context
